### ISSUE TITLE
Test all sharing tools once site is in development

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#16]
Because I'm limited by how much I can test the site locally, I need to test and bug fixes any social sharing errors that may occur once the site is in dev.

**Comment by kidcompassion** [comment]
@phillipadsmith I did some reading about Open Graph, and I did not realize that the facebook scraper doesn't read javascript, so it can't retrieve info from underscore templates or backbone generated URLs. This means that the desired behaviour, of being able to have unique meta tags for each individual card, can't be done in the way I had anticipated.

The workaround appears to be creating the url-specific meta tags on the server, but I don't know how to do this! Any advice?

**Comment by phillipadsmith** [comment]
> This means that the desired behaviour, of being able to have unique meta tags for each individual card, can't be done in the way I had anticipated.

Yes, indeed, you've got that right! :-) We discussed this quickly earlier in the week -- I know it's a blur already. ;-)

There are two parts to this:
1. Updating the meta-data when the /#show/[:id] route is triggered so that it's specific to one card. Have a look at how it's done for Bottom Lines here:
   https://github.com/TheTyee/bottom-lines/blob/master/ui/js/app.js#L33-L57

And then here:
https://github.com/TheTyee/bottom-lines/blob/master/ui/js/app.js#L114-L118
1. As you found, the "page" (which is actually generated on the client) needs to be rendered out so that Facebook's scraper sees the updated meta tags.

For Bottom Lines, we did this with a service called https://prerender.io/ and via a Tyee account that I set up at the time. I'll put the credentials in the usual spot.

Then, to make that all work, a .htacess file was added to catch requests from Facebook (and others) and respond to those with the pre-rendered page. It looks like this: https://gist.github.com/phillipadsmith/8bc9003307d4c76a80ed

Generally, you can poke around the prevew.bottomlines and bottomlines directory and see how that's all set-up as a good example of it working as you're after. :-)

Keep me updated!

**Comment by phillipadsmith** [comment]
Very quick update, as it's WAY TOO LATE and I'm off to bed. :-)

Be sure to pull the latest from `develop` as there are some significant changes:
- The index.html now runs anything that is "dynamic," i.e., letters, businesses, and the preview of three letters on the front page -- that means that Backbone routing can work as it is meant to now.
- The trick to the above is showing / hiding the various "panels" (divs) in index.html to make the page transition between states (front, letters, letter/show, businesses, and business/show). Have a look at App.Router and you'll see how that's working.
- PushState is working too, and the .htaccess will automagically be put back in place now when a push is made to `develop`
- I removed the Previous, Next, First, and Last links, as they didn't seem to useful. I put in a "More" link (needs styling love) that just adds more models to the collection and re-renders it. It's kinda like an "infinite scroll," but not.

There are some layout issues that I'm hoping you can attend to -- little tweaks mostly -- and some actual problems to fix that I'll need to open issues for tomorrow. 

And yet the app is working and should free you to move on to testing the sharing. Remember, there are no hash fragments or !#s now, so be sure to check that Prerender is not looking for them, etc.

Good luck & feel free to ping me on Skype with questions.
