### ISSUE TITLE
Set up dev/production URLs with GT

### ISSUE THREAD

**Issue by kidcompassion** [TheTyee/buylocal.thetyee.ca#17]
@phillipadsmith I'm a maroon and forgot about this completely until going to test my social tools. AM I safe in assuming I can handle the setup the same way as on The Housing Fix - i.e. just emailing GT with a desired url & user name?

**Comment by phillipadsmith** [comment]
@kidcompassion Until next week when I walk you through it, yes. :-)

However, given that this is a Tyee project, not TSS, it should probably just be domains under the username `tyeeapps` so it's with the other "apps" so to speak. 

FYI: I've got a micro service / API ready to go for you. It's running locally at the moment, and I've got it on my list to deploy on my Tyee day tomorrow.

I've loaded the 2014 entries, so that you've got 1000+ entries to play with in terms of displaying cards, paging, etc (which I'll help out with). 

Let me know if you have any questions. :-)

**Comment by phillipadsmith** [comment]
(Side note: I can also just set-up the domains for you, if you need them this eve / tmo am)

**Comment by kidcompassion** [comment]
@phillipadsmith That's awesome! It'll time out perfectly since I have almost all the UI stuff done and ready for testing. And I can take email GT in the morning, since I won't be actually working tomorrow until the afternoon - but if you find you to set them up for the microservice or anything, you're not stepping on my toes.

**Comment by phillipadsmith** [comment]
> That's awesome! It'll time out perfectly since I have almost all the UI stuff done and ready for testing. And I can take email GT in the morning, since I won't be actually working tomorrow until the afternoon - but if you find you to set them up for the microservice or anything, you're not stepping on my toes.

 :+1:
