### ISSUE TITLE
Pushing WIP on Backbone card management

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/buylocal.thetyee.ca#5]
Hey there @kidcompassion ,

Just heads-up that I'm aiming to push some work-in-progress on the card display via Backbone.js later today. I'll put it in a feature branch so that you can have a look without impacting your current work.

Let me know if you're in a good shape to have a look at that this week.

Phillip.

cc @MrBryan

**Comment by kidcompassion** [comment]
I'm all ready for it, have a bunch of CSS and doc top stuff running in
'setup' branch. Will be around this evening and all day tomorrow to keep
working on but local. :D

**Comment by phillipadsmith** [comment]
@kidcompassion :+1:

**Comment by phillipadsmith** [comment]
Howdy @kidcompassion --

Ran a bit behind yesterday. I've just pushed the example letter display to this feature branch: https://github.com/TheTyee/buylocal.thetyee.ca/tree/feature/basic-backbone-letter-display

Please check out that branch locally (save your in-progress work first). Once you've got it checked out, you should be able to just run Jekyll and see the basic example of the letters list at http://127.0.0.1:4000/letters/ and clicking a name in the list should switch to the single-letter view.

Let me know. :-)

**Comment by kidcompassion** [comment]
You're my hero, @phillipadsmith! This is so great. I've actually been doing a bunch of Backbone learning over the last week and built a prototype of my own (just to learn). But I got stuck at the list view, because I couldn't figure out the relationship between events, views and routes - so it's awesome to see how you did it. I actually made a throwaway branch just to see how this merges with my changes and it works great, just needs some CSS!

<img width="702" alt="screen shot 2015-11-03 at 5 07 26 pm" src="https://cloud.githubusercontent.com/assets/1507827/10925646/1cc51fca-824d-11e5-831d-1f3ebc441f43.png">
!

My next steps will be filling out the templates and adding styles, and then looking at pagination. Will let you know if I have any issues.

**Comment by phillipadsmith** [comment]
> My next steps will be filling out the templates and adding styles, and then looking at pagination. Will let you know if I have any issues.

@kidcompassion Cool. Glad it's working for you. And, yes, it should merge well.

Please keep pushing your changes up to GitHub regularly, as I may have a few more cycles to help with the Backbone bits.

Ideally , it would be great to:
- Move templates to their own .jst files to make them easier to work with and for compilation (Jekyll Assets will do that for us)
- Make the interaction between list view and detail view a bit less interdependent
- Update the meta tags on detail view

A lot of these concepts are here: https://github.com/BeautifulTrouble/solutions.thischangeseverything.org 

If you can keep your branch updated (or the master branch, as you're really the lead here) I can rebase from there and propose changes as we go.

Phillip.

**Comment by phillipadsmith** [comment]
Oh, and pagination won't make sense / work until there's data to page through, which is what I'm working on now...  ;-)
